sample_size: &sample_size 200
seed: &seed 43
order: 2 # order of local estimate
sigma: 1.0
figpath: 'figs'
name: 'e2_k1'

bandwidth_min: -1.9
bandwidth_max: 1
num_bandwidths: 30

kernel: 'rectangular'