sample_size: &sample_size 200
n_coef: *sample_size
seed: &seed 43
order: 3 # order of local estimate
sigma: 1.0
figpath: 'figs'
name: 'e3_k3'

bandwidth_min_log: -4.5
bandwidth_max_log: 1
num_bandwidths: 30

kernel: 'gaussian'
